/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaceJFRAME;

import Data.DataAkun;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import UserInterfaceJFRAME.Login;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.nio.file.Paths;
import java.util.logging.Level;

/**
 *
 * @author ASUS
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        USERTXT = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        USERTXT1 = new javax.swing.JLabel();
        usernameTXT1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        fullnameTXT = new javax.swing.JTextField();
        passwordTXT = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        kembaliBut = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        SignupButton1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PASSWORD");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, 10));

        USERTXT.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 13)); // NOI18N
        USERTXT.setForeground(new java.awt.Color(255, 255, 255));
        USERTXT.setText("FULL NAME");
        jPanel1.add(USERTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SPOTILIST");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 250, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 250, 10));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SIGN UP");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        USERTXT1.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 13)); // NOI18N
        USERTXT1.setForeground(new java.awt.Color(255, 255, 255));
        USERTXT1.setText("USERNAME");
        jPanel1.add(USERTXT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        usernameTXT1.setBackground(new java.awt.Color(22, 22, 22));
        usernameTXT1.setForeground(new java.awt.Color(255, 255, 255));
        usernameTXT1.setText("Username");
        usernameTXT1.setBorder(null);
        usernameTXT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTXT1ActionPerformed(evt);
            }
        });
        jPanel1.add(usernameTXT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 250, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 250, 10));

        fullnameTXT.setBackground(new java.awt.Color(22, 22, 22));
        fullnameTXT.setForeground(new java.awt.Color(255, 255, 255));
        fullnameTXT.setText("Full name");
        fullnameTXT.setBorder(null);
        fullnameTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameTXTActionPerformed(evt);
            }
        });
        jPanel1.add(fullnameTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 250, 30));

        passwordTXT.setBackground(new java.awt.Color(22, 22, 22));
        passwordTXT.setForeground(new java.awt.Color(255, 255, 255));
        passwordTXT.setText("kkdwodwdw");
        passwordTXT.setBorder(null);
        passwordTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTXTActionPerformed(evt);
            }
        });
        jPanel1.add(passwordTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 250, 20));

        jCheckBox1.setBackground(new java.awt.Color(22, 22, 22));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("I agree with terms and condition");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, -1, -1));

        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Created by Kelompok 3");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 620, -1, -1));

        kembaliBut.setBackground(new java.awt.Color(204, 0, 204));
        kembaliBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliButMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kembali");

        javax.swing.GroupLayout kembaliButLayout = new javax.swing.GroupLayout(kembaliBut);
        kembaliBut.setLayout(kembaliButLayout);
        kembaliButLayout.setHorizontalGroup(
            kembaliButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kembaliButLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        kembaliButLayout.setVerticalGroup(
            kembaliButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kembaliButLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel1.add(kembaliBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 600, 100, 30));

        SignupButton1.setBackground(new java.awt.Color(204, 0, 204));
        SignupButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignupButton1MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SIGN UP");

        javax.swing.GroupLayout SignupButton1Layout = new javax.swing.GroupLayout(SignupButton1);
        SignupButton1.setLayout(SignupButton1Layout);
        SignupButton1Layout.setHorizontalGroup(
            SignupButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupButton1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel11)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        SignupButton1Layout.setVerticalGroup(
            SignupButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignupButton1Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(SignupButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, -1, -1));

        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("List your fav and enjoy your songs");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 660, -1, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/bg - Copy.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.setToolTipText("");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2390, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 51));
        jLabel3.setText("|");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 20, 20));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/wallpaperflare.com_wallpaper (1).jpg"))); // NOI18N
        bg.setText("jLabel3");
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1209, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//   String nama;
//   String username;
//   String password;
//    
////Lengt
//   int PanjangNama = 50;
//   int Panjangusername = 50;
//    
////database
//   private Connection con;
//   private Statement stat;
//   private ResultSet res;  
//    public void register() {
//        initComponents();
//        koneksi();
//    }
//
//    public void koneksi() {
//        try {
//            Class.forName("com.mysql.jdbc.Driver");
//            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/minimarket", "root", "root");
//            stat = (Statement) con.createStatement();
//        }catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//    }
//}
//    public void bersih() {
//        usernameTXT.setText("");
//        usernameTXT1.setText("");
//        passwordTXT.setText("");
//    }
    

    private void fullnameTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameTXTActionPerformed

    private void passwordTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTXTActionPerformed

    private void kembaliButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliButMouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliButMouseClicked

    private void usernameTXT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTXT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTXT1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void SignupButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupButton1MouseClicked
        // TODO add your handling code here:
        DataAkun.inisialisasiDataAkun();
        String file = Paths.get("").toAbsolutePath().toString() + "\\data\\Akun.txt";
        File fl = new File(file);
        int b = 0;
        if(b == 0){
            for(int i = 0; i < DataAkun.akun.size(); i++){
                String usr = DataAkun.akun.get(i).getUsername();
                String usrtxt = usernameTXT1.getText();
                if(DataAkun.akun.get(i).getUsername().equals(usernameTXT1.getText())){
                    JOptionPane.showMessageDialog(null, "Maaf, Username telah digunakan");
                    fullnameTXT.setText("");
                    usernameTXT1.setText("");
                    passwordTXT.setText("");
                    usernameTXT1.requestFocus();
                    break;
                }else{
                    b++;
                }
            }
        }
        if(b == DataAkun.akun.size()){
            try{
                FileWriter fw = new FileWriter(fl, true);
                BufferedWriter bw = new BufferedWriter(fw);
                String name = fullnameTXT.getText();
                String usernamee = usernameTXT1.getText();
                String password = passwordTXT.getText();
                bw.write(name);
                bw.write("|");
                bw.write(usernamee);
                bw.write("|");
                bw.write(password);
                bw.newLine();
                bw.close();
                JOptionPane.showMessageDialog(null,"Selamat akun anda telah terdaftar");
                Login login = new Login();
                login.setVisible(true);
                dispose();
            
            }catch(Exception e){
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_SignupButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SignupButton1;
    private javax.swing.JLabel USERTXT;
    private javax.swing.JLabel USERTXT1;
    private javax.swing.JLabel bg;
    private javax.swing.JTextField fullnameTXT;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel kembaliBut;
    private javax.swing.JPasswordField passwordTXT;
    private javax.swing.JTextField usernameTXT1;
    // End of variables declaration//GEN-END:variables
}
